import { NextRequest, NextResponse } from "next/server";
export const runtime = "nodejs";
const schema = {type:"OBJECT",properties:{fields:{type:"OBJECT",properties:{registration_imo_no:{type:"STRING"},ship_name:{type:"STRING"},vessel_nationality:{type:"STRING"},crew_count:{type:"STRING"},local_agent_name:{type:"STRING"},arriving_from:{type:"STRING"}},required:["registration_imo_no","ship_name","vessel_nationality","crew_count","local_agent_name","arriving_from"]},arrival_date_text:{type:"STRING"},arrival_date_calendar:{type:"STRING",enum:["gregorian","hijri","unknown"]}},required:["fields","arrival_date_text","arrival_date_calendar"]};
function digits(s:string){return s.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))}
function validImo(s:string){if(!/^\d{7}$/.test(s))return false;return s.slice(0,6).split("").reduce((n,d,i)=>n+Number(d)*(7-i),0)%10===Number(s[6])}
function hijri(y:number,m:number,d:number){const f=new Intl.DateTimeFormat("en-u-ca-islamic-umalqura-nu-latn",{year:"numeric",month:"numeric",day:"numeric",timeZone:"UTC"});for(let t=Date.UTC(y+577,0,1);t<Date.UTC(y+580,0,1);t+=86400000){const p=Object.fromEntries(f.formatToParts(new Date(t)).map(x=>[x.type,x.value]));if(+p.year===y&&+p.month===m&&+p.day===d)return new Date(t).toISOString().slice(0,10)}return ""}
function isoDate(raw:string,cal:string){const a=digits(raw).match(/(\d{1,4})[/.\-](\d{1,2})[/.\-](\d{1,4})/);if(!a)return "";const p=a.slice(1).map(Number);let y:number,m:number,d:number;if(a[1].length>=4)[y,m,d]=p;else[d,m,y]=p;if(cal==="hijri"||(y>=1300&&y<=1600))return hijri(y,m,d);if(y<2000||y>2100||m<1||m>12||d<1||d>31)return "";const v=new Date(Date.UTC(y,m-1,d));return v.getUTCFullYear()===y&&v.getUTCMonth()===m-1&&v.getUTCDate()===d?v.toISOString().slice(0,10):""}
export async function POST(req:NextRequest){try{
 const key=process.env.GEMINI_API_KEY;if(!key)return NextResponse.json({error:"أضف GEMINI_API_KEY إلى متغيرات Netlify ثم أعد النشر"},{status:503});
 const token=req.headers.get("authorization")||"",url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!token.startsWith("Bearer ")||!url||!anon)return NextResponse.json({error:"سجّل الدخول أولًا"},{status:401});const auth=await fetch(url+"/auth/v1/user",{headers:{apikey:anon,Authorization:token}});if(!auth.ok)return NextResponse.json({error:"انتهت جلسة الدخول؛ سجّل الدخول مجددًا"},{status:401});
 const body=await req.json(),image=body?.image,mime=body?.mimeType;if(typeof image!=="string"||image.length>12000000||!["image/jpeg","image/png","image/webp"].includes(mime))return NextResponse.json({error:"الصورة غير مدعومة أو حجمها كبير"},{status:400});const lang=body.language==="eng"?"English":"Arabic";
 const prompt="Read this ship arrival notice image. User-selected language: "+lang+". Use one consistent reading context; do not combine OCR readings. Keep digits in printed order; never reverse/reorder. Extract only vessel name, IMO, nationality (الجنسية/جنسيتها only), crew count (عدد البحارة/البحارة/عدد طاقم البحارة/عدد الطاقم), agent/company (letterhead/logo), arriving-from (قادمة من/الجهة القادمة منها/From), and arrival date. Ignore cargo, call sign, destination, and long text. Copy IMO as exactly seven digits immediately beside its label; if unclear leave empty. Return exact date text and identify Hijri or Gregorian. Prefer arrival date over notice/signature dates. Never guess; leave unclear values empty. Return JSON matching schema.";
 const model=process.env.GEMINI_MODEL||"gemini-3.8-flash";const apiUrl="https://generativelanguage.googleapis.com/v1beta/models/"+model+":generateContent";const payload=JSON.stringify({contents:[{parts:[{text:prompt},{inline_data:{mime_type:mime,data:image}}]}],generationConfig:{responseMimeType:"application/json",responseSchema:schema,temperature:0}});let resp:Response|undefined;let result:any;let networkError=false;for(let attempt=0;attempt<3;attempt++){try{resp=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:payload,signal:AbortSignal.timeout(60000)});if(resp.ok){result=await resp.json();break}if(![429,500,502,503,504].includes(resp.status))break}catch(e){networkError=true}if(attempt<2)await new Promise(resolve=>setTimeout(resolve,800*(attempt+1)))}if(!resp?.ok){const retryable=networkError||[429,500,502,503,504].includes(resp?.status||0);const message=retryable?"Gemini مشغول أو الاتصال به متعثر مؤقتًا. انتظر قليلًا ثم أعد المحاولة.":"تعذر على Gemini معالجة الطلب. تحقق من مفتاح API وإعدادات النموذج.";return NextResponse.json({error:message},{status:retryable?503:502})}const text=result?.candidates?.[0]?.content?.parts?.find((p:{text?:string})=>p.text)?.text;if(!text)return NextResponse.json({error:"لم يُرجع Gemini بيانات قابلة للقراءة"},{status:502});const out=JSON.parse(text),fields=out.fields,warnings:string[]=[];
 fields.registration_imo_no=digits(fields.registration_imo_no||"").replace(/\D/g,"");if(!validImo(fields.registration_imo_no)){fields.registration_imo_no="";warnings.push("تحقق من رقم IMO يدويًا")};fields.crew_count=digits(fields.crew_count||"").replace(/\D/g,"").slice(0,3);if(Number(fields.crew_count)>500)fields.crew_count="";fields.expected_arrival_date=isoDate(out.arrival_date_text||"",out.arrival_date_calendar||"unknown");if(out.arrival_date_text&&!fields.expected_arrival_date)warnings.push("راجع التاريخ وأدخله يدويًا");return NextResponse.json({fields,warnings});
 }catch(e){console.error("Gemini arrival notice failed",e);return NextResponse.json({error:"حدث خطأ أثناء قراءة الإشعار"},{status:500})}}
