"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
type NoticeFields = { registration_imo_no:string; ship_name:string; vessel_nationality:string; crew_count:string; local_agent_name:string; arriving_from:string; expected_arrival_date:string };
const emptyFields = ():NoticeFields => ({ registration_imo_no:"", ship_name:"", vessel_nationality:"", crew_count:"", local_agent_name:"", arriving_from:"", expected_arrival_date:"" });
function imageAsBase64(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||"");const comma=value.indexOf(",");comma<0?reject(new Error("تعذر تجهيز الصورة")):resolve(value.slice(comma+1))};reader.onerror=()=>reject(new Error("تعذر قراءة ملف الصورة"));reader.readAsDataURL(file)})}
export default function ArrivalNoticeImporter({onApply}:{onApply:(fields:NoticeFields)=>void}){
 const [photo,setPhoto]=useState<File|null>(null);const [language,setLanguage]=useState<"ara"|"eng">("ara");const [fields,setFields]=useState<NoticeFields|null>(null);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const choosePhoto=(file?:File)=>{setPhoto(file||null);setFields(null);setStatus("")};
 const readPhoto=async()=>{if(!photo)return;setBusy(true);setStatus("إرسال الصورة إلى Gemini...");try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("سجّل الدخول أولًا لقراءة الإشعار");const response=await fetch("/api/maritime/arrival-notice",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({image:await imageAsBase64(photo),mimeType:photo.type||"image/jpeg",language})});const result=await response.json();if(!response.ok)throw new Error(result.error||"تعذرت قراءة الإشعار");setFields({...emptyFields(),...result.fields});setStatus(result.warnings?.length?"اكتملت القراءة؛ راجع: "+result.warnings.join("، "):"اكتملت القراءة باستخدام Gemini. راجع الحقول قبل التطبيق.")}catch(error:any){setStatus(error?.message||"تعذرت قراءة الصورة. حاول مرة أخرى.")}finally{setBusy(false)}};
 const updateField=(key:keyof NoticeFields,value:string)=>setFields(current=>current?{...current,[key]:value}:current);
 const labels:Record<keyof NoticeFields,string>={registration_imo_no:"رقم IMO / الرقم الدولي",ship_name:"اسم السفينة / الواسطة",vessel_nationality:"الجنسية",crew_count:"عدد الطاقم",local_agent_name:"الوكيل / الشركة",arriving_from:"قادمة من / الجهة القادمة منها",expected_arrival_date:"تاريخ الوصول"};
 return <section className="rounded-3xl border-2 border-blue-200 bg-blue-50 p-5 shadow"><h2 className="text-xl font-black text-slate-900">إدخال إشعار الوصول من صورة</h2><p className="mt-2 text-sm text-slate-700">اختر لغة الإشعار. يقرأ Gemini الصفحة ويركز على الحقول المطلوبة فقط.</p>
 <div className="mt-3 flex gap-2" role="group" aria-label="لغة القراءة"><button type="button" onClick={()=>{setLanguage("ara");setFields(null);setStatus("")}} className="rounded-lg border bg-white px-4 py-2 text-sm font-bold text-slate-700">قراءة بالعربية</button><button type="button" onClick={()=>{setLanguage("eng");setFields(null);setStatus("")}} className="rounded-lg border bg-white px-4 py-2 text-sm font-bold text-slate-700">Read in English</button></div>
 <div className="mt-4 flex flex-wrap items-center gap-3"><label className="cursor-pointer rounded-xl border border-blue-300 bg-white px-4 py-3 text-sm font-bold text-blue-900">فتح الكاميرا<input type="file" accept="image/*" capture="environment" className="sr-only" onChange={event=>choosePhoto(event.target.files?.[0])}/></label><label className="cursor-pointer rounded-xl border border-blue-300 bg-white px-4 py-3 text-sm font-bold text-blue-900">اختيار صورة<input type="file" accept="image/*" className="sr-only" onChange={event=>choosePhoto(event.target.files?.[0])}/></label><button type="button" disabled={!photo||busy} onClick={readPhoto} className="rounded-xl bg-blue-800 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"جاري القراءة...":"قراءة باستخدام Gemini"}</button>{photo&&<span className="text-xs text-slate-600">{photo.name}</span>}</div>
 {status&&<p className="mt-3 text-sm font-bold text-slate-700">{status}</p>}{fields&&<div className="mt-4 rounded-2xl border border-slate-200 bg-white p-4"><p className="mb-3 font-bold text-slate-800">الحقول المقروءة (يمكن تعديلها)</p><div className="grid gap-3 md:grid-cols-2">{(Object.keys(labels) as (keyof NoticeFields)[]).map(key=><label key={key} className="space-y-1 text-sm font-bold">{labels[key]}<input type={key==="expected_arrival_date"?"date":"text"} value={fields[key]} onChange={event=>updateField(key,event.target.value)} className="w-full rounded-lg border p-2" dir={key==="registration_imo_no"?"ltr":"auto"} inputMode={key==="registration_imo_no"||key==="crew_count"?"numeric":undefined}/></label>)}</div><button type="button" onClick={()=>onApply(fields)} className="mt-4 w-full rounded-xl bg-green-700 px-4 py-3 font-bold text-white hover:bg-green-800">تطبيق الحقول على النموذج للمراجعة</button><p className="mt-2 text-xs text-amber-800">لا تُحفظ المعاملة تلقائيًا. تحقق من رقم IMO والتاريخ قبل التطبيق.</p></div>}
 </section>;
}
